name: bmi_calculator
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hexcolor: ^2.0.7
  flutter_spinkit: ^5.1.0
  animated_text_kit: ^4.2.2
  liquid_pull_to_refresh: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  rename: ^2.0.1
  flutter_launcher_icons: ^0.10.0

flutter_icons:
    android: true
    ios: true
    image_path: "assets/app_logo.png"

flutter:
  uses-material-design: true

  assets:
     - assets/